name: Test
on:                                                                                                                                                           
  push:                                                                                                                                                       
    branches:                                                                                                                                                    
    - '*'
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.2
    - run: npm install
    - run: npm run test


